### ISSUE TITLE
Platform does not start if a micro application hangs during activation

### ISSUE THREAD

**Issue by jordiju** [SchweizerischeBundesbahnen/scion-microfrontend-platform#88]
## Describe the bug
The workbench stays on the startup animation indefinitely if one of the registered micro frontends runs into an error during startup/activation

## To Reproduce
1. Start an incognito window in Google Chrome (currently _not_ reproducible on Microsoft Edge)
2. Navigate to https://tms-test.sbb.ch/
3. Observe that the startup animation does not go away. The reason seems to be the error in the caparout micro app during its activation (see console log)

## Expected behavior
Activation errors in registered micro apps should be handled gracefully by the plattform, i.e. startup should complete with all micro apps loaded that could successfully be started. In this case: workbench is loaded with all micro apps except caparoute.

If this is not possible, there should be a timeout after which the user is informed that startup failed, with a reason. In this case: "Application could not be started due to error in micro app caparoute"

## Screenshots
![image](https://user-images.githubusercontent.com/37622418/125745193-311dad61-819e-4c06-b1af-b700886b8f44.png)

## Environment
Please complete the following information:

 - SCION Microfrontend Platform version: Version currently deployed on tms-test.sbb.ch
 - Browser: Chrome Version 91.0.4472.124
 - OS: Windows 10
 - Device:  Desktop

**Comment by danielwiehl** [comment]
Thank you @jordiju for reporting this issue.

This issue was fixed in #18, allowing you to configure a maximum timeout for loading manifests or waiting for activators to report readiness.  The timeout can be configured as global timeout or individual timeout per micro application. For more information, please refer to https://scion-microfrontend-platform-developer-guide.vercel.app/#chapter:platform-configuration:configuring-micro-applications.

For your project, please set the timeout(s) accordingly.

**Comment by jordiju** [comment]
Timeouts will be set in our project.
Closing this.
